version: "3.9"

services:
    stable-diffusion-webui:
        container_name: sd-webui
        build: .
        volumes:
            - models:/stable-diffusion/stable-diffusion-webui/models
            - extensions:/stable-diffusion/stable-diffusion-webui/extensions
        ports:
            - 7860:7860
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
volumes:
    models:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./models
    extensions:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./extensions